name: MyPosition
main: PocketEssential\MyPosition
version: 1.0.0
api: 2.1.0
Description: "Gets your XYZ ;)" 


commands:
 xyz:
  description: Main command for this plugin
  aliases: ["myposition", "cords", "cord", "position"] 

